version: "3.7"
services:
    admin_bot:
        build:
            context: .
            dockerfile: bot_admin.Dockerfile
        image: leelingzhen/telegram-admin-attendance-bot:dev
        container_name: alliance_admin_bot
        volumes:
            - .secrets:/attendance_bot/.secrets
            - ./resources:/attendance_bot/resources
    training_bot:
        build:
            context: .
            dockerfile: bot_training.Dockerfile
        image: leelingzhen/telegram-attendance-bot:dev
        container_name: alliance_training_bot
        volumes:
            - .secrets:/attendance_bot/.secrets
            - ./resources:/attendance_bot/resources
